api-allow-all: /api/**

base: /api/v1

endpoint:
  auth: ${base}/auth
  auth-logout: ${endpoint.auth}/logout
  #for demo
  management-allow-all: ${base}/management/**
  users: ${base}/users
  metadatas: ${base}/metadatas
  metadatas-search: ${endpoint.metadatas}/search
  favs: ${base}/favs
  series: ${base}/series
  episode: ${endpoint.series}/episode


  api:
    id: /{id}
    ip: /ip




origin:
  base: http://localhost
  port: 3000
  url: ${origin.base}:${origin.port}

header:
  authorization: 'Authorization'
  bearer_: 'Bearer '
